### ISSUE TITLE
Provide a action summary as output

### ISSUE THREAD

**Issue by florian-e-zeiss** [lcollins/checkstyle-github-action#218]
I like your implementation checkstyle and pmd action

If your provide the found results as output variable, than the user of our action is able to generate a nice STEP Summary.

Like:

```yaml

    outputs:
         conclusion:
             type: string
             description: Provide the conclusion 'success' | 'failure' | 'neutral' 
         violations:
             type: integer
             description: 'Number of found violations'
          failures:
             type: integer
             description: 'Number of found failures'
          warnings:
             type: integer
             description: 'Number of found warning'
          notice:
             type: integer
             description: 'Number of found notices'
          check_href:
              type: string
              description: 'Url to the generated checkstyle check https://....../runs/76145?check_suite_focus=true 
```
